version: '3'

services:
  postgresql_database:
    image: postgres:13-alpine
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "8000:5432"
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    networks:
      - orbit

volumes:
  pgsql-data:

networks:
  orbit: