name: CI test

on:
    push:
        branches: ["main", "dev"]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Test CI script
              run: echo new CI file is working
